lsi: false
safe: true
incremental: false
theme: minima
markdown: kramdown
highlighter: rouge
include:
  - search.json
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge