lsi: false
safe: true
incremental: false
theme: minima
markdown: kramdown
highlighter: rouge
baseurl: "/documentation"
include:
  - search.json
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-seo-tag
whitelist:
  - jekyll-seo-tag